/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is up. No auth.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description The database answers. No auth.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Rate limited per client IP (10/min by default).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the token pair
         * @description Refresh tokens are single use. Presenting an already-used one is treated as theft: every refresh token of that user is revoked. Rate limited per client IP.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out (revoke a refresh token)
         * @description Always 204. The access token stays valid until it expires (15 minutes by default); drop it on the client.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user (admin only)
         * @description There is no public sign-up: the first admin comes from ADMIN_EMAIL/ADMIN_PASSWORD, the rest are created here.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: operations["listServices"];
        put?: never;
        /** Create a service */
        post: operations["createService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a service */
        get: operations["getService"];
        put?: never;
        post?: never;
        /** Delete a service (admin only) */
        delete: operations["deleteService"];
        options?: never;
        head?: never;
        /** Update a service (partial) */
        patch: operations["updateService"];
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["listCustomers"];
        put?: never;
        /** Create a customer */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a customer */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        /** Delete a customer (admin only) */
        delete: operations["deleteCustomer"];
        options?: never;
        head?: never;
        /** Update a customer (partial) */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List appointments
         * @description `from`/`to` filter on the start day (business time zone, inclusive); both optional. Calendar view: ask for one week and sort is already by start.
         */
        get: operations["listAppointments"];
        put?: never;
        /**
         * Book an appointment
         * @description The single agenda cannot hold overlapping appointments; this is enforced atomically by the database, so of N simultaneous requests for one slot exactly one succeeds and the rest get 409.
         */
        post: operations["createAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get an appointment */
        get: operations["getAppointment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appointments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the status
         * @description `cancelled` and `no_show` free the time slot; `completed` keeps it.
         */
        patch: operations["setAppointmentStatus"];
        trace?: never;
    };
    "/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPIs of a period
         * @description All counts refer to appointments that START in the period. Omit `from`/`to` for the last 30 days ending today (business time zone).
         */
        get: operations["dashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily series
         * @description Days are calendar days in the business time zone. Omit `from`/`to` for the last 30 days ending today (business time zone).
         */
        get: operations["dashboardDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/top-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top services
         * @description Ordered by realized revenue (completed), then completed count, then total appointments, then name. Omit `from`/`to` for the last 30 days ending today (business time zone).
         */
        get: operations["dashboardTopServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming appointments */
        get: operations["dashboardUpcoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FieldError: {
            /**
             * @description Name of the offending field (dotted for nested ones).
             * @example starts_at
             */
            field: string;
            /** @example must be in the future */
            message: string;
        };
        /**
         * @description RFC 9457 problem details (`application/problem+json`).
         * @example {
         *       "type": "about:blank",
         *       "title": "Conflict",
         *       "status": 409,
         *       "detail": "That time slot overlaps another appointment.",
         *       "code": "slot_unavailable",
         *       "request_id": "5d1c1f1e-0a47-4c3c-a6c5-0f3d0f5f9b21"
         *     }
         */
        Problem: {
            /**
             * @description Always `about:blank`: the HTTP status says it all; branch on `code`.
             * @enum {string}
             */
            type: "about:blank";
            /**
             * @description The HTTP reason phrase.
             * @example Conflict
             */
            title: string;
            /** @example 409 */
            status: number;
            /** @example That time slot overlaps another appointment. */
            detail?: string;
            /**
             * @description Stable machine-readable error code.
             * @example slot_unavailable
             * @enum {string}
             */
            code: "invalid_json" | "validation_failed" | "body_too_large" | "unsupported_media_type" | "missing_token" | "invalid_token" | "invalid_credentials" | "forbidden" | "rate_limited" | "route_not_found" | "customer_not_found" | "service_not_found" | "appointment_not_found" | "email_taken" | "customer_in_use" | "service_in_use" | "slot_unavailable" | "invalid_transition" | "not_started" | "unknown_reference" | "service_inactive" | "timeout" | "not_ready" | "internal_error";
            /**
             * @description Same value as the X-Request-ID response header.
             * @example 5d1c1f1e-0a47-4c3c-a6c5-0f3d0f5f9b21
             */
            request_id?: string;
            /** @description Present on `validation_failed` (422): one entry per invalid field. */
            errors?: components["schemas"]["FieldError"][];
        };
        Health: {
            /** @example ok */
            status: string;
        };
        /**
         * @description `admin` can also delete services/customers and create users; `staff` cannot remove anything.
         * @enum {string}
         */
        Role: "admin" | "staff";
        User: {
            /**
             * Format: uuid
             * @example 0b7e9a51-2c3d-4e6f-8a90-b1c2d3e4f444
             */
            id: string;
            /**
             * Format: email
             * @example admin@example.com
             */
            email: string;
            role: components["schemas"]["Role"];
        };
        LoginRequest: {
            /**
             * Format: email
             * @example admin@example.com
             */
            email: string;
            /**
             * Format: password
             * @example dev-only-admin-password
             */
            password: string;
        };
        RefreshRequest: {
            /** @example Zm9vYmFyLXJlZnJlc2gtdG9rZW4tZXhhbXBsZS0wMDAwMDAwMDAwMDA */
            refresh_token: string;
        };
        TokenPair: {
            /** @description JWT (HS256), valid for `expires_in` seconds. Send as `Authorization: Bearer <token>`. */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /**
             * @description Access token lifetime in seconds.
             * @example 900
             */
            expires_in: number;
            /** @description Opaque, single use: every refresh returns a NEW pair and invalidates this token. Reusing an old one revokes all the user's sessions. */
            refresh_token: string;
        };
        NewUserRequest: {
            /**
             * Format: email
             * @example reception@example.com
             */
            email: string;
            /**
             * Format: password
             * @example a-long-enough-password
             */
            password: string;
            role: components["schemas"]["Role"];
        };
        /**
         * @example {
         *       "id": "3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111",
         *       "name": "Deep tissue massage",
         *       "description": "Slow, firm pressure for chronic tension.",
         *       "duration_min": 60,
         *       "price_cents": 12000,
         *       "active": true,
         *       "created_at": "2026-10-01T12:00:00Z",
         *       "updated_at": "2026-10-01T12:00:00Z"
         *     }
         */
        Service: {
            /**
             * Format: uuid
             * @example 3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111
             */
            id: string;
            /** @example Deep tissue massage */
            name: string;
            /** @example Slow, firm pressure for chronic tension. */
            description: string;
            /**
             * @description Duration in minutes.
             * @example 60
             */
            duration_min: number;
            /**
             * @description Price in cents of the (single) currency. Never a float.
             * @example 12000
             */
            price_cents: number;
            /**
             * @description Inactive services cannot be booked (existing appointments are unaffected).
             * @example true
             */
            active: boolean;
            /**
             * Format: date-time
             * @example 2026-10-01T12:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2026-10-01T12:00:00Z
             */
            updated_at: string;
        };
        /**
         * @example {
         *       "name": "Deep tissue massage",
         *       "description": "Slow, firm pressure for chronic tension.",
         *       "duration_min": 60,
         *       "price_cents": 12000
         *     }
         */
        ServiceInput: {
            /** @example Deep tissue massage */
            name: string;
            /** @example Slow, firm pressure for chronic tension. */
            description?: string;
            /** @example 60 */
            duration_min: number;
            /** @example 12000 */
            price_cents: number;
            /**
             * @description Optional; defaults to true.
             * @example true
             */
            active?: boolean;
        };
        /**
         * @description Partial update: send only the fields to change. Editing price/duration never alters existing appointments (they hold a snapshot).
         * @example {
         *       "price_cents": 13000
         *     }
         */
        ServicePatch: {
            name?: string;
            description?: string;
            duration_min?: number;
            price_cents?: number;
            active?: boolean;
        };
        /**
         * @example {
         *       "id": "9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222",
         *       "name": "Marina Duarte",
         *       "email": "marina.duarte@example.com",
         *       "phone": "31999990000",
         *       "notes": "Prefers a quiet room.",
         *       "created_at": "2026-10-01T12:05:00Z",
         *       "updated_at": "2026-10-01T12:05:00Z"
         *     }
         */
        Customer: {
            /**
             * Format: uuid
             * @example 9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222
             */
            id: string;
            /** @example Marina Duarte */
            name: string;
            /**
             * Format: email
             * @description Lower-cased; unique.
             * @example marina.duarte@example.com
             */
            email: string;
            /**
             * @description Digits only (empty when not given).
             * @example 31999990000
             */
            phone: string;
            /** @example Prefers a quiet room. */
            notes: string;
            /**
             * Format: date-time
             * @example 2026-10-01T12:05:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2026-10-01T12:05:00Z
             */
            updated_at: string;
        };
        /**
         * @example {
         *       "name": "Marina Duarte",
         *       "email": "marina.duarte@example.com",
         *       "phone": "(31) 99999-0000"
         *     }
         */
        CustomerInput: {
            /** @example Marina Duarte */
            name: string;
            /**
             * Format: email
             * @example marina.duarte@example.com
             */
            email: string;
            /**
             * @description Optional; 10 to 13 digits, formatting characters are accepted and stripped.
             * @example (31) 99999-0000
             */
            phone?: string;
            /** @example Prefers a quiet room. */
            notes?: string;
        };
        /**
         * @description Partial update: send only the fields to change.
         * @example {
         *       "notes": "Allergic to lavender."
         *     }
         */
        CustomerPatch: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            notes?: string;
        };
        /**
         * @description `scheduled` -> `completed` | `cancelled` | `no_show`. The last three are terminal.
         * @enum {string}
         */
        AppointmentStatus: "scheduled" | "completed" | "cancelled" | "no_show";
        /**
         * @example {
         *       "id": "c1d2e3f4-a5b6-4c78-9d01-e2f3a4b5c333",
         *       "customer_id": "9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222",
         *       "customer_name": "Marina Duarte",
         *       "service_id": "3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111",
         *       "service_name": "Deep tissue massage",
         *       "starts_at": "2026-10-07T17:00:00Z",
         *       "ends_at": "2026-10-07T18:00:00Z",
         *       "duration_min": 60,
         *       "price_cents": 12000,
         *       "status": "scheduled",
         *       "notes": "Prefers a quiet room.",
         *       "created_at": "2026-10-06T13:20:41.123456Z",
         *       "updated_at": "2026-10-06T13:20:41.123456Z"
         *     }
         */
        Appointment: {
            /**
             * Format: uuid
             * @example c1d2e3f4-a5b6-4c78-9d01-e2f3a4b5c333
             */
            id: string;
            /**
             * Format: uuid
             * @example 9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222
             */
            customer_id: string;
            /**
             * @description Current name of the customer (read-model field).
             * @example Marina Duarte
             */
            customer_name: string;
            /**
             * Format: uuid
             * @example 3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111
             */
            service_id: string;
            /**
             * @description SNAPSHOT of the service name at booking time.
             * @example Deep tissue massage
             */
            service_name: string;
            /**
             * Format: date-time
             * @description UTC instant. Show it in the business time zone (`timezone` in dashboard responses).
             * @example 2026-10-07T17:00:00Z
             */
            starts_at: string;
            /**
             * Format: date-time
             * @description `starts_at` + `duration_min`. Intervals are half-open: back-to-back appointments do not conflict.
             * @example 2026-10-07T18:00:00Z
             */
            ends_at: string;
            /**
             * @description SNAPSHOT of the service duration at booking time.
             * @example 60
             */
            duration_min: number;
            /**
             * @description SNAPSHOT of the service price at booking time.
             * @example 12000
             */
            price_cents: number;
            status: components["schemas"]["AppointmentStatus"];
            /** @example Prefers a quiet room. */
            notes: string;
            /**
             * Format: date-time
             * @example 2026-10-06T13:20:41.123456Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2026-10-06T13:20:41.123456Z
             */
            updated_at: string;
        };
        /**
         * @example {
         *       "customer_id": "9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222",
         *       "service_id": "3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111",
         *       "starts_at": "2026-10-07T14:00:00-03:00"
         *     }
         */
        AppointmentInput: {
            /**
             * Format: uuid
             * @example 9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222
             */
            customer_id: string;
            /**
             * Format: uuid
             * @description Must be an ACTIVE service.
             * @example 3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111
             */
            service_id: string;
            /**
             * Format: date-time
             * @description RFC 3339, must be in the future. Any offset is accepted; it is stored as UTC.
             * @example 2026-10-07T14:00:00-03:00
             */
            starts_at: string;
            /** @example Prefers a quiet room. */
            notes?: string;
        };
        /**
         * @example {
         *       "status": "completed"
         *     }
         */
        StatusInput: {
            /** @description Target status: `completed`, `no_show` (only once the appointment has started) or `cancelled`. */
            status: components["schemas"]["AppointmentStatus"];
        };
        Summary: {
            /**
             * Format: date
             * @description First day (inclusive), business time zone.
             * @example 2026-10-01
             */
            from: string;
            /**
             * Format: date
             * @description Last day (inclusive).
             * @example 2026-10-31
             */
            to: string;
            /** @example America/Sao_Paulo */
            timezone: string;
            /**
             * @description All appointments that START in the period, any status.
             * @example 42
             */
            appointments_total: number;
            by_status: {
                /** @example 10 */
                scheduled: number;
                /** @example 25 */
                completed: number;
                /** @example 4 */
                cancelled: number;
                /** @example 3 */
                no_show: number;
            };
            /**
             * @description REALIZED revenue: sum of the frozen prices of `completed` appointments.
             * @example 310000
             */
            revenue_cents: number;
            /**
             * @description revenue_cents / completed, rounded to the cent (0 when there are none).
             * @example 12400
             */
            average_ticket_cents: number;
            /**
             * @description cancelled / appointments_total, 0..1, 4 decimals (0 when there are none).
             * @example 0.0952
             */
            cancellation_rate: number;
            /**
             * @description no_show / appointments_total, 0..1, 4 decimals (0 when there are none).
             * @example 0.0714
             */
            no_show_rate: number;
            /**
             * @description Customers registered in the period.
             * @example 7
             */
            new_customers: number;
        };
        Day: {
            /**
             * Format: date
             * @example 2026-10-05
             */
            date: string;
            /**
             * @description All statuses.
             * @example 5
             */
            appointments: number;
            /** @example 3 */
            completed: number;
            /**
             * @description Completed only.
             * @example 36000
             */
            revenue_cents: number;
        };
        DailySeries: {
            /**
             * Format: date
             * @example 2026-10-01
             */
            from: string;
            /**
             * Format: date
             * @example 2026-10-31
             */
            to: string;
            /** @example America/Sao_Paulo */
            timezone: string;
            /** @description One point per calendar day of the period, zero-filled (no holes), ascending. */
            data: components["schemas"]["Day"][];
        };
        TopService: {
            /**
             * Format: uuid
             * @example 3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111
             */
            service_id: string;
            /** @example Deep tissue massage */
            name: string;
            /**
             * @description All statuses.
             * @example 14
             */
            appointments: number;
            /** @example 11 */
            completed: number;
            /**
             * @description Completed only.
             * @example 132000
             */
            revenue_cents: number;
        };
        Ranking: {
            /**
             * Format: date
             * @example 2026-10-01
             */
            from: string;
            /**
             * Format: date
             * @example 2026-10-31
             */
            to: string;
            /** @example America/Sao_Paulo */
            timezone: string;
            /** @description Ordered by realized revenue, then completed, then appointments, then name. */
            data: components["schemas"]["TopService"][];
        };
        UpcomingList: {
            /** @description Scheduled appointments from now on, soonest first. */
            data: components["schemas"]["Appointment"][];
        };
        ServiceList: {
            data: components["schemas"]["Service"][];
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
            /**
             * @description Total matches across all pages.
             * @example 12
             */
            total: number;
        };
        CustomerList: {
            data: components["schemas"]["Customer"][];
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
            /**
             * @description Total matches across all pages.
             * @example 57
             */
            total: number;
        };
        AppointmentList: {
            data: components["schemas"]["Appointment"][];
            /** @example 1 */
            page: number;
            /** @example 20 */
            page_size: number;
            /**
             * @description Total matches across all pages.
             * @example 31
             */
            total: number;
        };
    };
    responses: {
        /** @description The body is not valid JSON for this endpoint (`invalid_json`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid access token (`missing_token`, `invalid_token`); on login/refresh: `invalid_credentials` / `invalid_token`. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The role is not allowed to do this (`forbidden`): admin only. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Body larger than 1 MiB (`body_too_large`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Content-Type must be `application/json` (`unsupported_media_type`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded (`rate_limited`); see Retry-After. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until a request is allowed again. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected error (`internal_error`); the cause is logged, never returned. Quote `request_id`. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request exceeded its time budget (`timeout`) or a dependency is down (`not_ready`). */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Resource id. A malformed id answers 404, like an unknown one. */
        Id: string;
        Page: number;
        PageSize: number;
        /** @description Case-insensitive substring search (literal text; `%` and `_` have no special meaning). */
        Query: string;
        /**
         * @description First day, inclusive, `YYYY-MM-DD` in the business time zone.
         * @example 2026-10-01
         */
        From: string;
        /**
         * @description Last day, inclusive. `from`..`to` may span at most 366 days.
         * @example 2026-10-31
         */
        To: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Access + refresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Wrong e-mail or password (`invalid_credentials`). The same answer for an unknown e-mail. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A NEW access + refresh token pair; the presented refresh token is now spent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Unknown, expired, used or revoked refresh token (`invalid_token`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Revoked (idempotent: unknown tokens are ignored too) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description E-mail already registered (`email_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listServices: {
        parameters: {
            query?: {
                /** @description Filter by active/inactive; omit for both. */
                active?: boolean;
                /** @description Case-insensitive substring search (literal text; `%` and `_` have no special meaning). */
                q?: components["parameters"]["Query"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of services, ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Deep tissue massage",
                 *       "description": "Slow, firm pressure for chronic tension.",
                 *       "duration_min": 60,
                 *       "price_cents": 12000
                 *     }
                 */
                "application/json": components["schemas"]["ServiceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Path of the created resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Service not found (`service_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Service not found (`service_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Appointments reference it (`service_in_use`): deactivate it instead (PATCH `active: false`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "price_cents": 13000
                 *     }
                 */
                "application/json": components["schemas"]["ServicePatch"];
            };
        };
        responses: {
            /** @description The updated service */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Service not found (`service_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring search (literal text; `%` and `_` have no special meaning). */
                q?: components["parameters"]["Query"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of customers, ordered by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Marina Duarte",
                 *       "email": "marina.duarte@example.com",
                 *       "phone": "(31) 99999-0000"
                 *     }
                 */
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Path of the created resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description E-mail already registered (`email_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Customer not found (`customer_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Customer not found (`customer_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The customer has appointments (`customer_in_use`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "notes": "Allergic to lavender."
                 *     }
                 */
                "application/json": components["schemas"]["CustomerPatch"];
            };
        };
        responses: {
            /** @description The updated customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Customer not found (`customer_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description E-mail already registered (`email_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAppointments: {
        parameters: {
            query?: {
                status?: components["schemas"]["AppointmentStatus"];
                customer_id?: string;
                /**
                 * @description First day, inclusive, `YYYY-MM-DD` in the business time zone.
                 * @example 2026-10-01
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Last day, inclusive. `from`..`to` may span at most 366 days.
                 * @example 2026-10-31
                 */
                to?: components["parameters"]["To"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of appointments, ordered by start time (ascending) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    createAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "customer_id": "9a4e2d10-7b3c-4c55-8f61-2d7a6b5c2222",
                 *       "service_id": "3f6b1c7e-5d0a-4a52-9d2e-1c0b7e0a1111",
                 *       "starts_at": "2026-10-07T14:00:00-03:00"
                 *     }
                 */
                "application/json": components["schemas"]["AppointmentInput"];
            };
        };
        responses: {
            /** @description Booked: status `scheduled`, `ends_at` derived, name/duration/price snapshotted */
            201: {
                headers: {
                    /** @description Path of the created resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The slot overlaps another appointment (`slot_unavailable`), or the customer/service was just removed (`unknown_reference`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Validation failed (`validation_failed`: past start, unknown customer/service, malformed ids) or the service is inactive (`service_inactive`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    getAppointment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The appointment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Appointment not found (`appointment_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    setAppointmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id. A malformed id answers 404, like an unknown one. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "completed"
                 *     }
                 */
                "application/json": components["schemas"]["StatusInput"];
            };
        };
        responses: {
            /** @description The updated appointment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Appointment not found (`appointment_not_found`), or the id is malformed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not allowed from the current status (`invalid_transition`: only `scheduled` moves), or `completed`/`no_show` before the start time (`not_started`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unknown status value (`validation_failed`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    dashboardSummary: {
        parameters: {
            query?: {
                /**
                 * @description First day, inclusive, `YYYY-MM-DD` in the business time zone.
                 * @example 2026-10-01
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Last day, inclusive. `from`..`to` may span at most 366 days.
                 * @example 2026-10-31
                 */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    dashboardDaily: {
        parameters: {
            query?: {
                /**
                 * @description First day, inclusive, `YYYY-MM-DD` in the business time zone.
                 * @example 2026-10-01
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Last day, inclusive. `from`..`to` may span at most 366 days.
                 * @example 2026-10-31
                 */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One point per day, zero-filled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySeries"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    dashboardTopServices: {
        parameters: {
            query?: {
                /**
                 * @description First day, inclusive, `YYYY-MM-DD` in the business time zone.
                 * @example 2026-10-01
                 */
                from?: components["parameters"]["From"];
                /**
                 * @description Last day, inclusive. `from`..`to` may span at most 366 days.
                 * @example 2026-10-31
                 */
                to?: components["parameters"]["To"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ranking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    dashboardUpcoming: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduled appointments from now on, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Validation failed (`validation_failed`): `errors` lists each invalid field. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
}
